### ISSUE TITLE
HDD Temperature

### ISSUE THREAD

**Issue by lee-costa** [rumart/grafana-dashboards#3]
Greetings and thank you for the dashboard!

I was wondering how are you retrieving HDD temperatures from FreeNAS? I am also using graphite as in your guide but don't see HDD temperatures in the database. 

I assume you must be using a script?

**Comment by rumart** [comment]
Hi,
Very sorry about the late response.
I'm not using any custom scripts, I've just configured the remote graphite server in freenas.
Might be that your disks is not providing temperature readings? Do you see them in the freenas ui?

**Comment by lee-costa** [comment]
I don't see that information on my reporting tab in FreeNAS. Its either my disks not reporting or the fact that I am still on 11.1-U7?

**Comment by rumart** [comment]
I'm on 11.2 now, but I believe I had access to that info on previous versions as well.
Can you see the temp readings in the reporting section in your FreeNAS UI?

**Comment by lee-costa** [comment]
I cannot see it on the UI either. So is it up to the drive to report that information?

**Comment by rumart** [comment]
What kind of disks do you have?

**Comment by lee-costa** [comment]
I have four Seagate 2TB ST2000DM008.

**Comment by rumart** [comment]
Ok, I'm not familiar with those. I use WD in my setup.
Not sure, but might be that you have to enable S.M.A.R.T tests for your drives if that's not already been done. 
If that doesn't help I would try to get some help in the [FreeNAS forum](https://www.ixsystems.com/community/categories/freenas.1/)
